// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Regenerated when files in actions/ change.
// This file augments the ActionRegistry interface so that useActionQuery and
// useActionMutation infer the correct types from your action definitions.

/** Extract the return type and parameter type from a defineAction module. */
type ActionEntry<T> = T extends { default: { run: (...args: infer A) => infer R } }
  ? {
      result: Awaited<R>;
      params: A extends [infer P, ...any[]] ? P : Record<string, any>;
    }
  : { result: any; params: Record<string, any> };

declare global {
  interface AgentNativeActionRegistry {
    "course-grid": ActionEntry<typeof import("../actions/course-grid")>;
    "course-summary": ActionEntry<typeof import("../actions/course-summary")>;
    "create-assessment": ActionEntry<typeof import("../actions/create-assessment")>;
    "create-class": ActionEntry<typeof import("../actions/create-class")>;
    "create-course": ActionEntry<typeof import("../actions/create-course")>;
    "delete-assessment": ActionEntry<typeof import("../actions/delete-assessment")>;
    "delete-class": ActionEntry<typeof import("../actions/delete-class")>;
    "delete-course": ActionEntry<typeof import("../actions/delete-course")>;
    "delete-student": ActionEntry<typeof import("../actions/delete-student")>;
    "exportar-alumnos-md": ActionEntry<typeof import("../actions/exportar-alumnos-md")>;
    "exportar-alumnos-vcard": ActionEntry<typeof import("../actions/exportar-alumnos-vcard")>;
    "genera-carpetas-alumnos": ActionEntry<typeof import("../actions/genera-carpetas-alumnos")>;
    "generate-classes": ActionEntry<typeof import("../actions/generate-classes")>;
    "hello": ActionEntry<typeof import("../actions/hello")>;
    "list-assessments": ActionEntry<typeof import("../actions/list-assessments")>;
    "list-classes": ActionEntry<typeof import("../actions/list-classes")>;
    "list-courses": ActionEntry<typeof import("../actions/list-courses")>;
    "list-students": ActionEntry<typeof import("../actions/list-students")>;
    "navigate": ActionEntry<typeof import("../actions/navigate")>;
    "publicar-enunciado-trabajo": ActionEntry<typeof import("../actions/publicar-enunciado-trabajo")>;
    "set-assessment-result": ActionEntry<typeof import("../actions/set-assessment-result")>;
    "set-attendance": ActionEntry<typeof import("../actions/set-attendance")>;
    "student-summary": ActionEntry<typeof import("../actions/student-summary")>;
    "update-assessment": ActionEntry<typeof import("../actions/update-assessment")>;
    "update-class": ActionEntry<typeof import("../actions/update-class")>;
    "update-course": ActionEntry<typeof import("../actions/update-course")>;
    "upsert-student": ActionEntry<typeof import("../actions/upsert-student")>;
    "view-screen": ActionEntry<typeof import("../actions/view-screen")>;
    "work-grid": ActionEntry<typeof import("../actions/work-grid")>;
    "get-feature-flags": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/get-feature-flags")>;
    "list-feature-flags": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/list-feature-flags")>;
    "set-feature-flag": ActionEntry<typeof import("@agent-native/core/feature-flags/actions/set-feature-flag")>;
    "share-resource": ActionEntry<typeof import("@agent-native/core/sharing/actions/share-resource")>;
    "unshare-resource": ActionEntry<typeof import("@agent-native/core/sharing/actions/unshare-resource")>;
    "list-resource-shares": ActionEntry<typeof import("@agent-native/core/sharing/actions/list-resource-shares")>;
    "set-resource-visibility": ActionEntry<typeof import("@agent-native/core/sharing/actions/set-resource-visibility")>;
    "upload-image": ActionEntry<typeof import("@agent-native/core/file-upload/actions/upload-image")>;
    "context-manifest-get": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-manifest-get")>;
    "context-pin": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-pin")>;
    "context-evict": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-evict")>;
    "context-restore": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-restore")>;
    "context-report": ActionEntry<typeof import("@agent-native/core/agent/context-xray/actions/context-report")>;
    "get-localization-preference": ActionEntry<typeof import("@agent-native/core/localization/actions/get-localization-preference")>;
    "set-localization-preference": ActionEntry<typeof import("@agent-native/core/localization/actions/set-localization-preference")>;
    "create-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/create-resource-version")>;
    "list-resource-versions": ActionEntry<typeof import("@agent-native/core/history/actions/list-resource-versions")>;
    "get-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/get-resource-version")>;
    "restore-resource-version": ActionEntry<typeof import("@agent-native/core/history/actions/restore-resource-version")>;
    "list-resource-history": ActionEntry<typeof import("@agent-native/core/history/actions/list-resource-history")>;
    "list-review-comments": ActionEntry<typeof import("@agent-native/core/review/actions/list-review-comments")>;
    "create-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/create-review-comment")>;
    "reply-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/reply-review-comment")>;
    "resolve-review-thread": ActionEntry<typeof import("@agent-native/core/review/actions/resolve-review-thread")>;
    "delete-review-comment": ActionEntry<typeof import("@agent-native/core/review/actions/delete-review-comment")>;
    "consume-review-feedback": ActionEntry<typeof import("@agent-native/core/review/actions/consume-review-feedback")>;
    "get-review-feedback": ActionEntry<typeof import("@agent-native/core/review/actions/get-review-feedback")>;
    "set-review-status": ActionEntry<typeof import("@agent-native/core/review/actions/set-review-status")>;
    "send-review-thread-to-agent": ActionEntry<typeof import("@agent-native/core/review/actions/send-review-thread-to-agent")>;
  }
}

declare module "@agent-native/core/client" {
  interface ActionRegistry extends AgentNativeActionRegistry {}
}

declare module "@agent-native/core/client/hooks" {
  interface ActionRegistry extends AgentNativeActionRegistry {}
}

export {};
