// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Static-import registry of every action file. Bundlers (Nitro, Rolldown)
// see these imports and include the action modules in the server bundle.
// The agent-chat plugin normalizes each module into an ActionEntry shape.
import * as a_course_grid from "../actions/course-grid";
import * as a_course_summary from "../actions/course-summary";
import * as a_create_assessment from "../actions/create-assessment";
import * as a_create_class from "../actions/create-class";
import * as a_create_course from "../actions/create-course";
import * as a_delete_assessment from "../actions/delete-assessment";
import * as a_delete_class from "../actions/delete-class";
import * as a_delete_course from "../actions/delete-course";
import * as a_delete_student from "../actions/delete-student";
import * as a_exportar_alumnos_md from "../actions/exportar-alumnos-md";
import * as a_exportar_alumnos_vcard from "../actions/exportar-alumnos-vcard";
import * as a_genera_carpetas_alumnos from "../actions/genera-carpetas-alumnos";
import * as a_generate_classes from "../actions/generate-classes";
import * as a_hello from "../actions/hello";
import * as a_list_assessments from "../actions/list-assessments";
import * as a_list_classes from "../actions/list-classes";
import * as a_list_courses from "../actions/list-courses";
import * as a_list_students from "../actions/list-students";
import * as a_navigate from "../actions/navigate";
import * as a_publicar_enunciado_trabajo from "../actions/publicar-enunciado-trabajo";
import * as a_set_assessment_result from "../actions/set-assessment-result";
import * as a_set_attendance from "../actions/set-attendance";
import * as a_student_summary from "../actions/student-summary";
import * as a_update_assessment from "../actions/update-assessment";
import * as a_update_class from "../actions/update-class";
import * as a_update_course from "../actions/update-course";
import * as a_upsert_student from "../actions/upsert-student";
import * as a_view_screen from "../actions/view-screen";
import * as a_work_grid from "../actions/work-grid";
import * as a_get_feature_flags from "@agent-native/core/feature-flags/actions/get-feature-flags";
import * as a_list_feature_flags from "@agent-native/core/feature-flags/actions/list-feature-flags";
import * as a_set_feature_flag from "@agent-native/core/feature-flags/actions/set-feature-flag";
import * as a_share_resource from "@agent-native/core/sharing/actions/share-resource";
import * as a_unshare_resource from "@agent-native/core/sharing/actions/unshare-resource";
import * as a_list_resource_shares from "@agent-native/core/sharing/actions/list-resource-shares";
import * as a_set_resource_visibility from "@agent-native/core/sharing/actions/set-resource-visibility";
import * as a_upload_image from "@agent-native/core/file-upload/actions/upload-image";
import * as a_context_manifest_get from "@agent-native/core/agent/context-xray/actions/context-manifest-get";
import * as a_context_pin from "@agent-native/core/agent/context-xray/actions/context-pin";
import * as a_context_evict from "@agent-native/core/agent/context-xray/actions/context-evict";
import * as a_context_restore from "@agent-native/core/agent/context-xray/actions/context-restore";
import * as a_context_report from "@agent-native/core/agent/context-xray/actions/context-report";
import * as a_get_localization_preference from "@agent-native/core/localization/actions/get-localization-preference";
import * as a_set_localization_preference from "@agent-native/core/localization/actions/set-localization-preference";
import * as a_create_resource_version from "@agent-native/core/history/actions/create-resource-version";
import * as a_list_resource_versions from "@agent-native/core/history/actions/list-resource-versions";
import * as a_get_resource_version from "@agent-native/core/history/actions/get-resource-version";
import * as a_restore_resource_version from "@agent-native/core/history/actions/restore-resource-version";
import * as a_list_resource_history from "@agent-native/core/history/actions/list-resource-history";
import * as a_list_review_comments from "@agent-native/core/review/actions/list-review-comments";
import * as a_create_review_comment from "@agent-native/core/review/actions/create-review-comment";
import * as a_reply_review_comment from "@agent-native/core/review/actions/reply-review-comment";
import * as a_resolve_review_thread from "@agent-native/core/review/actions/resolve-review-thread";
import * as a_delete_review_comment from "@agent-native/core/review/actions/delete-review-comment";
import * as a_consume_review_feedback from "@agent-native/core/review/actions/consume-review-feedback";
import * as a_get_review_feedback from "@agent-native/core/review/actions/get-review-feedback";
import * as a_set_review_status from "@agent-native/core/review/actions/set-review-status";
import * as a_send_review_thread_to_agent from "@agent-native/core/review/actions/send-review-thread-to-agent";

const modules: Record<string, unknown> = {
  "course-grid": a_course_grid,
  "course-summary": a_course_summary,
  "create-assessment": a_create_assessment,
  "create-class": a_create_class,
  "create-course": a_create_course,
  "delete-assessment": a_delete_assessment,
  "delete-class": a_delete_class,
  "delete-course": a_delete_course,
  "delete-student": a_delete_student,
  "exportar-alumnos-md": a_exportar_alumnos_md,
  "exportar-alumnos-vcard": a_exportar_alumnos_vcard,
  "genera-carpetas-alumnos": a_genera_carpetas_alumnos,
  "generate-classes": a_generate_classes,
  "hello": a_hello,
  "list-assessments": a_list_assessments,
  "list-classes": a_list_classes,
  "list-courses": a_list_courses,
  "list-students": a_list_students,
  "navigate": a_navigate,
  "publicar-enunciado-trabajo": a_publicar_enunciado_trabajo,
  "set-assessment-result": a_set_assessment_result,
  "set-attendance": a_set_attendance,
  "student-summary": a_student_summary,
  "update-assessment": a_update_assessment,
  "update-class": a_update_class,
  "update-course": a_update_course,
  "upsert-student": a_upsert_student,
  "view-screen": a_view_screen,
  "work-grid": a_work_grid,
  "get-feature-flags": a_get_feature_flags,
  "list-feature-flags": a_list_feature_flags,
  "set-feature-flag": a_set_feature_flag,
  "share-resource": a_share_resource,
  "unshare-resource": a_unshare_resource,
  "list-resource-shares": a_list_resource_shares,
  "set-resource-visibility": a_set_resource_visibility,
  "upload-image": a_upload_image,
  "context-manifest-get": a_context_manifest_get,
  "context-pin": a_context_pin,
  "context-evict": a_context_evict,
  "context-restore": a_context_restore,
  "context-report": a_context_report,
  "get-localization-preference": a_get_localization_preference,
  "set-localization-preference": a_set_localization_preference,
  "create-resource-version": a_create_resource_version,
  "list-resource-versions": a_list_resource_versions,
  "get-resource-version": a_get_resource_version,
  "restore-resource-version": a_restore_resource_version,
  "list-resource-history": a_list_resource_history,
  "list-review-comments": a_list_review_comments,
  "create-review-comment": a_create_review_comment,
  "reply-review-comment": a_reply_review_comment,
  "resolve-review-thread": a_resolve_review_thread,
  "delete-review-comment": a_delete_review_comment,
  "consume-review-feedback": a_consume_review_feedback,
  "get-review-feedback": a_get_review_feedback,
  "set-review-status": a_set_review_status,
  "send-review-thread-to-agent": a_send_review_thread_to_agent,
};

export default modules;
