@GROQ_API_KEY = XX
@BASE_URL = https://api.groq.com/openai/v1
@MODEL = openai/gpt-oss-120b

POST {{BASE_URL}}/chat/completions
Content-Type: application/json
Authorization: Bearer {{GROQ_API_KEY}}

{
  "messages": [
    {
        "role": "user",
        "content": "¿Qué edad tiene Messi?"
    }
  ],
  "model": "{{MODEL}}",
  "stream": false
} 
